server:
  port: 8080
  servlet:
    context-path: /employee-service/api
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: employee-service

addressservice:
  base:
    url: http://localhost:8081/address-service/api

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

# żeby odblokować endpoint /actuator/info:
management:
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: true
# domyślnie będzie pusto. Trzeba dodać jakieś informacje:
info:
  name: To jest jakaś apka
  version: 1.234.4

