spring:
  data:
    mongodb:
      uri: mongodb://root:admin@localhost:27017
      database: microservices
      username: root
      password: admin
  application:
    name: rating-service
server:
  port: 8083
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

# Okta configuration for api gateway
okta:
  oauth2:
    issuer: https://dev-91507242.okta.com/oauth2/default
    audience: api://default