server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  application:
    name: user-service
  config:
    import: configserver:http://localhost:8085
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-91507242.okta.com/oauth2/default
      client:
        registration:
          my-internal-client:
            provider: okta
            authorization-grant-type: client_credentials
            scope:
              - internal
            client-id: 0oaakums1g3Kni7FK5d7
            client-secret: 6Ri2LgC78w407_7MrdeTme5x8o_kZft-SjSIVar0ga1Q-Y_aov7gHPV0mez_Ij_4
        provider:
          okta:
            issuer-uri: https://dev-91507242.okta.com/oauth2/default


# TEN ZAKOMENTOWANY PROPERTIS JEST ZACIĄGANY Z SERWERA (Z REPO - GITHUB):
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka

# Circuit Breaker (Resilience4J)
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    jmx:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
resilience4j:
  circuitbreaker:
    instances:
      ratingHotelBreaker:
        register-health-indicator: true
        event-consumer-buffer-size: 10
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 6s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        sliding-window-type: count_based
  retry:
    instances:
      ratingHotelService:
        max-attempts: 3
        wait-duration: 5s
  ratelimiter:
    instances:
      userRateLimiter:
        limit-refresh-period: 4s
        limit-for-period: 2
        timeout-duration: 2s

# Okta configuration for api gateway
okta:
  oauth2:
    issuer: https://dev-91507242.okta.com/oauth2/default
    audience: api://default

