server:
  port: 8082
spring:
  application:
    name: notification
  datasource:
    url: jdbc:postgresql://localhost:5432/notification
    username: root
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  profiles:
    active: default

#RabbitMQ:
  rabbitmq:
    addresses: localhost:5672

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

#do zipkina ważne, żeby wyświetlał wszystkie info:
management:
  tracing:
    sampling:
      probability: 1.0

#RabbitMQ (customowe):
rabbitmq:
  exchanges:
    internal: internal.exchange
  queues:
    notification: notification.queue
  routing-keys:
    internal-notification: internal.notification.routing-key
