spring:
  application:
    name: notification-service
#  zipkin:
#    base-url: http://localhost:9411
#  sleuth:
#    integration:
#      enabled: true
#    sampler:
#      probability: 1.0
  cloud:
    compatibility-verifier:
      enabled: false
#Kafka Properties
  kafka:
    bootstrap-servers: localhost:9092
    template:
      default-topic: notificationTopic
    consumer:
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring.json.type.mapping: "event:notificationservice.OrderPlacedEvent"
      group-id: notificationId
server:
  port: 0
eureka:
  client:
    service-url:
      defaultZone: http://eureka:password@localhost:8761/eureka
management:
  tracing:
    propagation:
      type: b3, w3c
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411
