server:
  port: 8222
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: student-service
          uri: http://localhost:8090
          predicates:
            - Path=/api/v1/students/**
        - id: school-service
          uri: http://localhost:8070
          predicates:
            - Path=/api/v1/schools/**
  application:
    name: gateway

#do zipkina ważne, żeby wyświetlał wszystkie info:
management:
  tracing:
    sampling:
      probability: 1.0
