eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8070

spring:
  application:
    name: school-service
  datasource:
    url: jdbc:postgresql://localhost:5432/schools
    username: root
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
application:
  config:
    students-url: http://localhost:8222/api/v1/students

#do zipkina ważne, żeby wyświetlał wszystkie info:
management:
  tracing:
    sampling:
      probability: 1.0