eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8090

spring:
  application:
    name: student-service
  datasource:
    url: jdbc:postgresql://localhost:5431/students
    username: root
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

#do zipkina ważne, żeby wyświetlał wszystkie info:
management:
  tracing:
    sampling:
      probability: 1.0