server:
  port: 9292

# TE SAME PROPERTISY SĄ ZDEFINIOWANE W KLASIE KONFIGURACYJNEJ JAKO DRUGA MOŻLIWOŚĆ:
#spring:
#  kafka:
#    consumer:
#      bootstrap-servers: localhost:9092
#      group-id: grupa1
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
#      properties:
#        spring:
#          json:
#            trusted:
#              packages: com.example.kafka.dto
