spring:
  data:
    mongodb:
      host: localhost
      port: 27017
#      uri: mongodb://localhost/test
      database: test
      username: root
      password: example
      authentication-database: admin
  application:
    name: product-service
#  zipkin:
#    base-url: http://localhost:9411
#  sleuth:
#    sampler:
#      probability: 1.0
  cloud:
    compatibility-verifier:
      enabled: false
eureka:
  client:
    service-url:
      defaultZone: http://eureka:password@localhost:8761/eureka
server:
  port: 0
management:
  tracing:
    propagation:
      type: b3, w3c
    sampling:
      probability: 1.0
