spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: admin
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
welcome:
  message: Witaj witaj.

# w actuatorze jest lista dostępnych opcji/statystyk (endpointów)
# możemy wykluczyć (exclude) już istniejące endpointy, żeby się tam nie wyświetlały
# albo zawrzeć (include) nowe endpointy, które mają się tam wyświetlać
management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env,beans"


