spring:
  datasource:
    url: jdbc:h2:mem:test;DATABASE_TO_UPPER=false
  jpa:
    show-sql: true

#    mo?liwo?? zmiany nazewnictwa kolumn na takie same jak klasie
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl