eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: student-service-route
          uri: lb://student-service
          predicates:
            - Path=/students/**
        - id: school-service-route
          uri: lb://school-service
          predicates:
            - Path=/schools/**
        - id: teacher-service-route
          uri: lb://teacher-service
          predicates:
            - Path=/teachers/**
server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: "*"