server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/testdb
    password: admin
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: hotel-service
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka