spring:
  datasource:
    url: jdbc:mysql://localhost:3306/inventory-service
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
  application:
    name: inventory-service
#  zipkin:
#    base-url: http://localhost:9411
#  sleuth:
#    sampler:
#      probability: 1.0
  cloud:
    compatibility-verifier:
      enabled: false
server:
  port: 8082
eureka:
  client:
    service-url:
      defaultZone: http://eureka:password@localhost:8761/eureka
management:
  tracing:
    propagation:
      type: b3, w3c
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411
