server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/inventory-service
    username: lukas
    password: password
eureka:
  client:
    service-url:
      defaultZone: http://eureka:password@discovery-server:8761/eureka
management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9411