server:
  port: 8081
spring:
  application:
    name: fraud
  datasource:
    url: jdbc:postgresql://localhost:5432/fraud
    username: root
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  profiles:
    active: default
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

#do zipkina ważne, żeby wyświetlał wszystkie info:
management:
  tracing:
    sampling:
      probability: 1.0

